# Test fmristore adapter integration
# These tests use synthetic test fixtures generated by helpers-generate-test-fixtures.R

test_that("fmristore test fixtures exist or can be generated", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  testdata_dir <- test_path("testdata")

  # Check if fixtures exist, generate if not
  fixtures <- list(
    labeled_volume = file.path(testdata_dir, "labeled_volume_small.h5"),
    parcellated = file.path(testdata_dir, "parcellated_small.h5"),
    latent_vec = file.path(testdata_dir, "latent_vec_small.lv.h5")
  )

  # Generate missing fixtures
  if (!all(file.exists(unlist(fixtures)))) {
    message("\nGenerating missing test fixtures...")
    source(test_path("helpers-generate-test-fixtures.R"))
    generate_all_fmristore_fixtures()
  }

  # Verify all exist
  expect_true(file.exists(fixtures$labeled_volume))
  expect_true(file.exists(fixtures$parcellated))
  expect_true(file.exists(fixtures$latent_vec))
})


test_that("fmristore adapter detects LabeledVolumeSet layout", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/labeled_volume_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  # Test detection
  score <- .fmri_detect(fixture)
  expect_true(is.numeric(score))
  expect_equal(score, 0.95)  # Should detect as fmristore layout
})


test_that("fmristore adapter can open LabeledVolumeSet", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/labeled_volume_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  # Test open
  handle <- .fmri_open(fixture, mode = "r")

  expect_type(handle, "list")
  expect_true("h5" %in% names(handle))
  expect_true(inherits(handle$h5, "H5File"))

  # Cleanup
  handle$h5$close_all()
})


test_that("fmristore adapter can probe LabeledVolumeSet", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/labeled_volume_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  handle <- .fmri_open(fixture, mode = "r")
  on.exit(handle$h5$close_all())

  # Test probe
  probe_result <- .fmri_probe(handle)

  expect_type(probe_result, "list")
  expect_true("assays" %in% names(probe_result))
  expect_true("dims" %in% names(probe_result))
  expect_true("subjects" %in% names(probe_result))
  expect_true("contrasts" %in% names(probe_result))
  expect_true("space" %in% names(probe_result))

  # Check dimensions
  expect_length(probe_result$dims, 3)
  expect_named(probe_result$dims, c("sample", "subject", "contrast"))

  # Should have 2 contrasts (contrast_A, contrast_B)
  expect_equal(unname(probe_result$dims["contrast"]), 2)
  expect_equal(probe_result$contrasts, c("contrast_A", "contrast_B"))

  # Check space
  expect_s3_class(probe_result$space, "Space")
  expect_equal(probe_result$space$type, "voxel")
})


test_that("fmristore adapter can read LabeledVolumeSet data", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/labeled_volume_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  handle <- .fmri_open(fixture, mode = "r")
  on.exit(handle$h5$close_all())

  probe_result <- .fmri_probe(handle)

  # Test read - all data
  data <- .fmri_read(
    handle = handle,
    assays = "beta",
    block = NULL,
    probe_result = probe_result
  )

  expect_type(data, "list")
  expect_true("beta" %in% names(data))

  # Check dimensions [sample, subject, contrast]
  beta_data <- data$beta
  expect_equal(dim(beta_data)[1], unname(probe_result$dims["sample"]))
  expect_equal(dim(beta_data)[2], unname(probe_result$dims["subject"]))
  expect_equal(dim(beta_data)[3], unname(probe_result$dims["contrast"]))

  # Data should be numeric
  expect_true(is.numeric(beta_data))
  expect_false(any(is.na(beta_data)))
})


test_that("fmristore adapter can read LabeledVolumeSet with block", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/labeled_volume_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  handle <- .fmri_open(fixture, mode = "r")
  on.exit(handle$h5$close_all())

  probe_result <- .fmri_probe(handle)

  # Test read with contrast block (only first contrast)
  data <- .fmri_read(
    handle = handle,
    assays = "beta",
    block = list(contrast = 1),
    probe_result = probe_result
  )

  expect_type(data, "list")
  expect_true("beta" %in% names(data))

  # Should only have 1 contrast
  beta_data <- data$beta
  expect_equal(dim(beta_data)[3], 1)
})


test_that("fmristore adapter detects H5ParcellatedScan layout", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/parcellated_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  # Test detection
  score <- .fmri_detect(fixture)
  expect_true(is.numeric(score))
  expect_equal(score, 0.95)
})


test_that("fmristore adapter can probe H5ParcellatedScan", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/parcellated_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  handle <- .fmri_open(fixture, mode = "r")
  on.exit(handle$h5$close_all())

  # Test probe
  probe_result <- .fmri_probe(handle)

  expect_type(probe_result, "list")
  expect_true("space" %in% names(probe_result))

  # Should be parcels space
  expect_s3_class(probe_result$space, "Space")
  expect_equal(probe_result$space$type, "parcels")
})


test_that("fmristore adapter detects LatentNeuroVec layout", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")
  skip_if_not_installed("Matrix")

  fixture <- test_path("testdata/latent_vec_small.lv.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  # Test detection
  score <- .fmri_detect(fixture)
  expect_true(is.numeric(score))
  expect_equal(score, 0.95)
})


test_that("fmristore adapter can probe LatentNeuroVec", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")
  skip_if_not_installed("Matrix")

  fixture <- test_path("testdata/latent_vec_small.lv.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  handle <- .fmri_open(fixture, mode = "r")
  on.exit(handle$h5$close_all())

  # Test probe
  probe_result <- .fmri_probe(handle)

  expect_type(probe_result, "list")
  expect_true("space" %in% names(probe_result))

  # Should be basis space
  expect_s3_class(probe_result$space, "Space")
  expect_equal(probe_result$space$type, "basis")

  # Should have k=3 components
  expect_equal(unname(probe_result$dims["sample"]), 3)
})


test_that("fmristore adapter closes handles properly", {
  skip_if_not_installed("neuroim2")
  skip_if_not_installed("fmristore")
  skip_if_not_installed("hdf5r")

  fixture <- test_path("testdata/labeled_volume_small.h5")
  skip_if_not(file.exists(fixture), "Test fixture not available")

  handle <- .fmri_open(fixture, mode = "r")

  # Close should work without error
  expect_silent(.fmri_close(handle))

  # Handle should no longer be valid
  expect_false(handle$h5$is_valid)
})


test_that("fmristore adapter handles /gds group (Path B)", {
  skip_if_not_installed("hdf5r")

  # Create a temporary file with /gds group
  tmpfile <- tempfile(fileext = ".h5")
  on.exit(unlink(tmpfile))

  h5 <- hdf5r::H5File$new(tmpfile, mode = "w")
  h5$create_group("/gds")
  h5$close_all()

  # Should detect as score 1.0 (delegates to h5 adapter)
  score <- .fmri_detect(tmpfile)
  expect_equal(score, 1.0)
})
