// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_omp_threads
void set_omp_threads(const int n);
RcppExport SEXP _fmrigds_set_omp_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    set_omp_threads(n);
    return R_NilValue;
END_RCPP
}
// meta_fe_cpp
Rcpp::List meta_fe_cpp(const arma::mat& beta, const arma::mat& var, const int min_subj, const double eps, const int tail);
RcppExport SEXP _fmrigds_meta_fe_cpp(SEXP betaSEXP, SEXP varSEXP, SEXP min_subjSEXP, SEXP epsSEXP, SEXP tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const int >::type tail(tailSEXP);
    rcpp_result_gen = Rcpp::wrap(meta_fe_cpp(beta, var, min_subj, eps, tail));
    return rcpp_result_gen;
END_RCPP
}
// meta_re_dl_cpp
Rcpp::List meta_re_dl_cpp(const arma::mat& beta, const arma::mat& var, const int min_subj, const double eps, const int tail);
RcppExport SEXP _fmrigds_meta_re_dl_cpp(SEXP betaSEXP, SEXP varSEXP, SEXP min_subjSEXP, SEXP epsSEXP, SEXP tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const int >::type tail(tailSEXP);
    rcpp_result_gen = Rcpp::wrap(meta_re_dl_cpp(beta, var, min_subj, eps, tail));
    return rcpp_result_gen;
END_RCPP
}
// meta_fe_reg_cpp
Rcpp::List meta_fe_reg_cpp(const arma::mat& beta, const arma::mat& var, const arma::mat& X, const int min_subj, const double eps);
RcppExport SEXP _fmrigds_meta_fe_reg_cpp(SEXP betaSEXP, SEXP varSEXP, SEXP XSEXP, SEXP min_subjSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(meta_fe_reg_cpp(beta, var, X, min_subj, eps));
    return rcpp_result_gen;
END_RCPP
}
// meta_re_reg_dl_cpp
Rcpp::List meta_re_reg_dl_cpp(const arma::mat& beta, const arma::mat& var, const arma::mat& X, const int min_subj, const double eps);
RcppExport SEXP _fmrigds_meta_re_reg_dl_cpp(SEXP betaSEXP, SEXP varSEXP, SEXP XSEXP, SEXP min_subjSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(meta_re_reg_dl_cpp(beta, var, X, min_subj, eps));
    return rcpp_result_gen;
END_RCPP
}
// stouffer_combine_cpp
Rcpp::List stouffer_combine_cpp(const arma::mat& z, Rcpp::Nullable<Rcpp::NumericVector> weights, const int min_subj);
RcppExport SEXP _fmrigds_stouffer_combine_cpp(SEXP zSEXP, SEXP weightsSEXP, SEXP min_subjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    rcpp_result_gen = Rcpp::wrap(stouffer_combine_cpp(z, weights, min_subj));
    return rcpp_result_gen;
END_RCPP
}
// fisher_combine_cpp
Rcpp::List fisher_combine_cpp(const arma::mat& pmat, const int min_subj);
RcppExport SEXP _fmrigds_fisher_combine_cpp(SEXP pmatSEXP, SEXP min_subjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_combine_cpp(pmat, min_subj));
    return rcpp_result_gen;
END_RCPP
}
// lancaster_combine_cpp
Rcpp::List lancaster_combine_cpp(const arma::mat& pmat, const Rcpp::IntegerVector dfw, const int min_subj);
RcppExport SEXP _fmrigds_lancaster_combine_cpp(SEXP pmatSEXP, SEXP dfwSEXP, SEXP min_subjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type dfw(dfwSEXP);
    Rcpp::traits::input_parameter< const int >::type min_subj(min_subjSEXP);
    rcpp_result_gen = Rcpp::wrap(lancaster_combine_cpp(pmat, dfw, min_subj));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmrigds_set_omp_threads", (DL_FUNC) &_fmrigds_set_omp_threads, 1},
    {"_fmrigds_meta_fe_cpp", (DL_FUNC) &_fmrigds_meta_fe_cpp, 5},
    {"_fmrigds_meta_re_dl_cpp", (DL_FUNC) &_fmrigds_meta_re_dl_cpp, 5},
    {"_fmrigds_meta_fe_reg_cpp", (DL_FUNC) &_fmrigds_meta_fe_reg_cpp, 5},
    {"_fmrigds_meta_re_reg_dl_cpp", (DL_FUNC) &_fmrigds_meta_re_reg_dl_cpp, 5},
    {"_fmrigds_stouffer_combine_cpp", (DL_FUNC) &_fmrigds_stouffer_combine_cpp, 3},
    {"_fmrigds_fisher_combine_cpp", (DL_FUNC) &_fmrigds_fisher_combine_cpp, 2},
    {"_fmrigds_lancaster_combine_cpp", (DL_FUNC) &_fmrigds_lancaster_combine_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmrigds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
