# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lmm_ri_objective_cpp <- function(Y, X, n_repeat, lambda, fit = "REML") {
    .Call(`_fmrigds_lmm_ri_objective_cpp`, Y, X, n_repeat, lambda, fit)
}

lmm_ri_fit_cpp <- function(Y, X, n_repeat, lambda, fit = "REML") {
    .Call(`_fmrigds_lmm_ri_fit_cpp`, Y, X, n_repeat, lambda, fit)
}

lmm_lowrank_objective_cpp <- function(Y, X, U_block, fit = "REML") {
    .Call(`_fmrigds_lmm_lowrank_objective_cpp`, Y, X, U_block, fit)
}

lmm_lowrank_fit_cpp <- function(Y, X, U_block, fit = "REML") {
    .Call(`_fmrigds_lmm_lowrank_fit_cpp`, Y, X, U_block, fit)
}

set_omp_threads <- function(n) {
    invisible(.Call(`_fmrigds_set_omp_threads`, n))
}

meta_fe_cpp <- function(beta, var, min_subj = 2L, eps = 1e-12, tail = 0L) {
    .Call(`_fmrigds_meta_fe_cpp`, beta, var, min_subj, eps, tail)
}

meta_re_dl_cpp <- function(beta, var, min_subj = 2L, eps = 1e-12, tail = 0L) {
    .Call(`_fmrigds_meta_re_dl_cpp`, beta, var, min_subj, eps, tail)
}

meta_fe_reg_cpp <- function(beta, var, X, min_subj = 2L, eps = 1e-12) {
    .Call(`_fmrigds_meta_fe_reg_cpp`, beta, var, X, min_subj, eps)
}

meta_re_reg_dl_cpp <- function(beta, var, X, min_subj = 2L, eps = 1e-12) {
    .Call(`_fmrigds_meta_re_reg_dl_cpp`, beta, var, X, min_subj, eps)
}

stouffer_combine_cpp <- function(z, weights = NULL, min_subj = 1L) {
    .Call(`_fmrigds_stouffer_combine_cpp`, z, weights, min_subj)
}

fisher_combine_cpp <- function(pmat, min_subj = 1L) {
    .Call(`_fmrigds_fisher_combine_cpp`, pmat, min_subj)
}

lancaster_combine_cpp <- function(pmat, dfw, min_subj = 1L) {
    .Call(`_fmrigds_lancaster_combine_cpp`, pmat, dfw, min_subj)
}

